import type { Metadata } from 'next'
import ApolloWrapper from '@/lib/ApolloWrapper'
import './globals.css'
import { UserProvider } from '@/components/Utils/context/userContext'

export const metadata: Metadata = {
  title: 'Skattframtal | Ísland.is',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="is">
      <body>
        <ApolloWrapper>
          <UserProvider>{children}</UserProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
